### ISSUE TITLE
this package is not installing

### ISSUE THREAD

**Issue by jsoneaday** [rill-js/polyfill#1]
I'm trying to run the todomvc-react package and this one npm package is not installing. The message I see is I:\code\ml-sports\todomvc-react\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\dharr\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\dharr\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ). I can see other packages under @rill like react but not this one.

**Comment by jsoneaday** [comment]
installed dev tools for windows and python but now getting new error. 

i:\code\ml-sports\todomvc-react\node_modules\ursa\src\ursanative.cc(1271): error C2027: use of undefined type 'rsa_st' [I:\Code\ml-sports\todomvc-react\node_modules\ursa\build\ursaNative.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(321,5): error MSB3491: Could not write lines to file "Release\obj\zopfli\zopfli.tlog\zopfli.lastbuildstate". The process cannot access the file 'I:\Code\ml-sports\todomvc-react\node_modules\node-zop
fli\build\Release\obj\zopfli\zopfli.tlog\zopfli.lastbuildstate' because it is being used by another process. [I:\Code\ml-sports\todomvc-react\node_modules\node-zopfli\build\zopfli.vcxproj]

**Comment by DylanPiercey** [comment]
Looks like it's related to this https://github.com/Financial-Times/polyfill-service/issues/1785

This module doesn't currently work on Node 10, so we will just have to wait 😢.
Let's track this over there.

**Comment by DylanPiercey** [comment]
Also if you are using the rill/react todomvc I'd recommend just not using the polyfill for now or running with node 8/9 until the module gets patched.

**Comment by DylanPiercey** [comment]
Scratch the last message, I went ahead and updated all of the dependencies in the todomvc examples (webpack 4, Babel 7, etc) and am now relying on the autopolyfilling from Babel env instead of this. Will consider switching it back once node 10 support arrives.
